name: 基金数据爬取与分析

on:
  schedule:
    - cron: '0 9,15,21 * * 1-5'  # 工作日9点、15点、21点执行
  workflow_dispatch:  # 手动触发
  push:
    branches: [ main ]

jobs:
  fund-analysis:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout代码
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}

    - name: 设置Python环境
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: 设置时区
      run: |
        sudo timedatectl set-timezone Asia/Shanghai

    - name: 运行基金数据爬取
      env:
        REPO_ACCESS_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
      run: |
        python src/main.py

    - name: 提交分析结果
      env:
        REPO_ACCESS_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        if git diff --staged --quiet; then
          echo "没有新的变化"
        else
          git commit -m "自动更新基金分析报告 $(date '+%Y-%m-%d %H:%M:%S')"
          git push https://x-access-token:${{ secrets.REPO_ACCESS_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
        fi

    - name: 发送通知
      if: always()
      run: |
        python src/notification.py "${{ job.status }}"
