name: Daily Model Training

on:
  schedule:
    - cron: '0 22 * * *'  # 每天UTC 22:00运行（北京时间次日6:00）
  workflow_dispatch:       # 允许手动触发

jobs:
  train-model:
    runs-on: ubuntu-latest
    timeout-minutes: 180   # 最长运行3小时
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install system dependencies
      run: |
        # 添加TA-Lib的官方仓库
        sudo add-apt-repository ppa:taurus/taurus -y
        sudo apt-get update -qq
        
        # 安装必要的开发库
        sudo apt-get install -y \
          libta-lib-dev \
          build-essential \
          python3-dev
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel  # 确保有wheel包
        pip install -r requirements.txt
        
    - name: Fetch new data
      run: |
        python src/data_loader.py \
          --fund 000311.OF \
          --start_date $(date -d "2 years ago" +%Y-%m-%d) \
          --output data/raw/latest.csv
          
    - name: Preprocess data
      run: |
        python src/preprocess.py \
          --input data/raw/latest.csv \
          --output data/processed/training_data.parquet
          
    - name: Train model
      run: |
        python src/train_model.py \
          --data data/processed/training_data.parquet \
          --output models/latest_model.pt \
          --epochs 50 \
          --seq_len 30
          
    - name: Run backtest
      run: |
        python src/backtest.py \
          --model models/latest_model.pt \
          --data data/processed/training_data.parquet \
          --output results/backtest_report.html
          
    - name: Upload results
      uses: actions/upload-artifact@v4
      with:
        name: training-results
        path: |
          models/latest_model.pt
          results/backtest_report.html
