name: Daily Model Training

on:
  schedule:
    - cron: '0 22 * * *'  # 每天UTC 22:00运行
  workflow_dispatch:       # 允许手动触发

jobs:
  train-model:
    runs-on: ubuntu-latest
    timeout-minutes: 180   # 最长运行3小时
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y \
          build-essential \
          wget \
          libatlas-base-dev \
          python3-dev \
          gfortran \
          libopenblas-dev \
          liblapack-dev
        
        wget https://downloads.sourceforge.net/project/ta-lib/ta-lib/0.4.0/ta-lib-0.4.0-src.tar.gz
        tar -xzf ta-lib-0.4.0-src.tar.gz
        cd ta-lib
        ./configure --prefix=/usr
        make
        sudo make install
        cd ..
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --no-cache-dir torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
        pip install -r requirements.txt
        
    - name: Create directories
      run: |
        mkdir -p data/raw
        mkdir -p data/processed
        mkdir -p models
        mkdir -p results
        
    - name: Fetch new data
      run: |
        # 计算开始日期
        START_DATE=$(date -d "2 years ago" +%Y-%m-%d)
        echo "开始日期: $START_DATE"
        
        # 使用正确的基金代码
        python src/data_loader.py \
          --fund 510300.SS \  # 修正为正确的沪深300ETF基金代码
          --start_date "$START_DATE" \
          --output data/raw/latest.csv
          
    - name: Check data file
      run: |
        # 检查文件是否非空
        if [ ! -s "data/raw/latest.csv" ]; then
          echo "错误: 数据文件为空或不存在!"
          ls -la data/raw
          exit 1
        fi
          
    - name: Preprocess data
      run: |
        python src/preprocess.py \
          --input data/raw/latest.csv \
          --output data/processed/training_data.parquet
          
    - name: Verify preprocessed data
      run: |
        if [ ! -f "data/processed/training_data.parquet" ]; then
          echo "错误: 预处理后的数据文件未找到!"
          ls -la data/processed
          exit 1
        fi
        
    - name: Train model
      run: |
        python src/train_model.py \
          --data data/processed/training_data.parquet \
          --output models/latest_model.pt \
          --epochs 50 \
          --seq_len 30
          
    - name: Run backtest
      run: |
        python src/backtest.py \
          --model models/latest_model.pt \
          --data data/processed/training_data.parquet \
          --output results/backtest_report.html
          
    - name: Upload results
      uses: actions/upload-artifact@v4
      with:
        name: training-results
        path: |
          models/latest_model.pt
          results/backtest_report.html
