name: 基金数据分析与买卖点生成

on:
  schedule:
    # 每个交易日下午2点运行（北京时间，UTC+8，对应UTC时间早上6点）
    - cron: '0 6 * * 1-5'
  workflow_dispatch: # 允许手动触发

jobs:
  analyze-funds:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}

      - name: 设置Python环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 pandas numpy pytz

      - name: 运行基金分析脚本
        run: python fund_analysis.py

      - name: 提交更改
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git diff --staged --quiet || git commit -m "更新基金买卖点分析表 $(date '+%Y-%m-%d %H:%M:%S')"
          git push
