name: Fund Analysis Daily

on:
  schedule:
    # 每天北京时间下午2点运行 (UTC时间6点)
    - cron: '0 6 * * *'
  workflow_dispatch: # 允许手动触发

jobs:
  analyze-funds:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pandas numpy schedule beautifulsoup4 lxml
    
    - name: Run fund analysis
      run: python fund_analysis.py
    
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md fund_history.json
        git commit -m "更新基金买卖点数据 $(date '+%Y-%m-%d %H:%M')" || echo "没有变化需要提交"
        git push origin main
