name: Fund Crawl & AI Analysis

on:
  schedule:
    # 每天 02:00 UTC（你可改） -> GitHub 用 UTC
    - cron: '0 2 * * *'
  workflow_dispatch: {}  # 手动触发

jobs:
  run-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run fetch and analyze
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          # 可选：若要 push 分析结果回 repo，需要设置 PERSONAL_TOKEN（建议用专门的 PAT）
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python scripts/fetch_and_analyze.py --fund-list funds.txt --output results/analysis_$(date +%Y%m%d_%H%M%S).json

      - name: Upload Results as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: fund-analysis-results
          path: results/*.json
