name: 代理节点爬取与Clash订阅生成

on:
  schedule:
    # 每天北京时间8:00运行 (UTC+8，对应UTC 0:00)
    - cron: '0 0 * * *'
  workflow_dispatch: # 允许手动触发

jobs:
  scrape-and-generate:
    runs-on: ubuntu-latest
    steps:
      - name: 检出仓库
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}

      - name: 设置Python环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 lxml pyyaml asyncio aiohttp speedtest-cli

      - name: 运行代理节点爬取脚本
        run: python scraper.py

      - name: 提交更改
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add subscription.yml
          git diff --staged --quiet || git commit -m "更新Clash订阅配置 $(date '+%Y-%m-%d %H:%M:%S')"
          git push
